version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.0
    environment:
      - GO111MODULE: "on"
    working_directory: /go/src/github.com/tombell/saga
    steps:
      - checkout
      - run: make test
      - run: make cibuild
