version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - run: make test
      - run: make coverage
      - storage_artifacts:
          path: dist/coverage.html
          destination: coverage.html
