name: Run Tests

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Run tests
      run: make testv
